# RetailCo — MC2: LangChain Churn Classifier + Outreach Generator
**FDE Engineering Track · Session 2**

> *It is Tuesday. The data is clean. The client wants to see AI working by Friday.*  
> *The sales team uses Slack and Google Sheets — not Jupyter notebooks.*  
> *Whatever you build has to run in their world, not yours.*

---
### What this notebook does
1. Reads today's CSV from a Google Drive folder called **Daily Report of Sales**
2. Runs a 2-step LangChain chain on every customer row
3. Chain 1 classifies churn risk (high / medium / low)
4. Chain 2 generates a personalised outreach message
5. Writes the results back to a Google Sheet the sales team can read

### Architecture
```
Google Drive (Daily Report of Sales/)
    └── 2024-06-07.csv   ← data team drops this every night
            ↓
    Colab reads today's file by date
            ↓
    LangChain Chain 1 → classifies risk
            ↓
    LangChain Chain 2 → generates message
            ↓
    Google Sheet (Results tab) ← n8n reads this at 9 AM
            ↓
    Slack alert for high-risk customers
```
---

## Cell 1 — Install dependencies

In [ ]:
!pip install langchain langchain-openai gspread gspread-dataframe --quiet
print('✅ Dependencies installed')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.6/99.6 kB 6.7 MB/s eta 0:00:00
✅ Dependencies installed

## Cell 2 — Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
print('✅ Google Drive mounted')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Google Drive mounted

In [28]:
from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive')

import os

folder = '/content/drive/MyDrive/Daily Report of Sales'
print("geme status:", os.path.exists(folder))
print("PP or F:", os.listdir(folder) if os.path.exists(folder) else "FOLDER NOT FOUND")

Mounted at /content/drive
geme status: False
PP or F: FOLDER NOT FOUND

## Cell 3 — Config
Set your folder path, Google Sheet ID, and API key here. Everything else is automatic.

In [43]:
import os
from datetime import date

# ── CONFIG — edit these three lines only ──────────────────────────────────
DRIVE_FOLDER   = '/content/drive/MyDrive/ Daily Report of Sales'
SHEET_ID       = ''   # paste from Sheet URL
OPENAI_API_KEY = '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'     # or use Claude API key
# ─────────────────────────────────────────────────────────────────────────

TODAY          = date.today().isoformat()       # e.g. 2026-06-07
CSV_FILENAME   = f'{TODAY}.csv'
CSV_PATH       = os.path.join(DRIVE_FOLDER, CSV_FILENAME)

os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

print(f'✅ Config loaded')
print(f'   Looking for: {CSV_PATH}')
print(f'   Today       : {TODAY}')

✅ Config loaded
   Looking for: /content/drive/MyDrive/ Daily Report of Sales/2026-06-07.csv
   Today       : 2026-06-07

## Cell 4 — Read today's CSV from Google Drive

> **How this works for the client:**  
> Every night the data team exports from the CRM and saves the file as `YYYY-MM-DD.csv` into the **Daily Report of Sales** folder in Google Drive.  
> This cell reads whichever file matches today's date automatically — no manual file selection.

In [27]:
import pandas as pd

# Check the file exists
if not os.path.exists(CSV_PATH):
    # Fallback: list what IS in the folder so we can debug
    available = os.listdir(DRIVE_FOLDER) if os.path.exists(DRIVE_FOLDER) else []
    raise FileNotFoundError(
        f"No file found for today ({CSV_FILENAME}).\n"
        f"Files in folder: {available}\n"
        f"Make sure the data team saved today's export as: {CSV_FILENAME}"
    )

df = pd.read_csv(CSV_PATH)

print(f'✅ Loaded: {CSV_FILENAME}')
print(f'   Rows    : {len(df):,}')
print(f'   Columns : {list(df.columns)}')
print()
df.head()

✅ Loaded: 2026-06-07.csv
   Rows    : 200
   Columns : ['customer_id', 'purchase_count_90d', 'days_since_last_purchase', 'avg_order_value', 'top_product_category', 'churn_label']

,customer_id,purchase_count_90d,days_since_last_purchase,avg_order_value,top_product_category,churn_label
0,C1001,8,3,245.50,Electronics,0
1,C1002,1,67,89.00,Clothing,1
2,C1003,6,5,312.75,Groceries,0
3,C1004,2,54,125.00,Electronics,1
4,C1005,9,2,198.25,Clothing,0

## Cell 5 — Build Chain 1: Churn Risk Classifier

> **Why two chains instead of one?**  
> Separating classification from message generation means you can debug each step independently.  
> If the message is wrong, you know whether the classification was right first.

In [52]:
!pip install -q langchain-openai azure-identity

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.1/192.1 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.9/220.9 kB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.7/123.7 kB 9.2 MB/s eta 0:00:00

In [56]:
from langchain_openai import AzureChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field

# ── Azure OpenAI config — paste your values here ──────────────────────────
AZURE_ENDPOINT  = "https://iitrfde.services.ai.azure.com/openai"
DEPLOYMENT_NAME = "gpt-5.4-nano"
API_VERSION     = "2024-12-01-preview"
AZURE_API_KEY   = "15FnUEqi6oqmbc64XV5wx2GC7mudfwMLmk8GkYPhRlEtTh8pDCXYJQQJ99CFACYeBjFXJ3w3AAAAACOGkLqq"
# ─────────────────────────────────────────────────────────────────────────

llm = AzureChatOpenAI(
    azure_endpoint=AZURE_ENDPOINT,
    azure_deployment=DEPLOYMENT_NAME,
    api_version=API_VERSION,
    api_key=AZURE_API_KEY,
    temperature=0
)

print("✅ Azure OpenAI connected —", DEPLOYMENT_NAME)

✅ Azure OpenAI connected — gpt-5.4-nano

In [59]:
from openai import OpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field
import json

# ── Azure AI Foundry config — from your deployment details
ENDPOINT    = "https://iitrfde.services.ai.azure.com/openai/v1"
MODEL       = "gpt-5.4-nano"
API_KEY     = "15FnUEqi6oqmbc64XV5wx2GC7mudfwMLmk8GkYPhRlEtTh8pDCXYJQQJ99CFACYeBjFXJ3w3AAAAACOGkLqq"
# ─────────────────────────────────────────────────────────────────────────

client = OpenAI(
    base_url=ENDPOINT,
    api_key=API_KEY
)

print("Azure OpenAI client ready —", MODEL)

# ── Classification function (replaces LangChain chain)
def classify_churn(purchase_count_90d, days_since_last_purchase, avg_order_value):
    prompt = f"""
You are a customer churn analyst.

Given this customer's behaviour over the last 90 days:
- Purchases made: {purchase_count_90d}
- Days since last purchase: {days_since_last_purchase}
- Average order value: ${avg_order_value}

Classify this customer's churn risk as high, medium, or low.
Rules:
- High: 1-2 purchases OR 60+ days since last purchase
- Medium: 3-5 purchases AND 30-59 days since last purchase
- Low: 6+ purchases AND fewer than 30 days since last purchase

Return ONLY valid JSON. No markdown, no code blocks.
Example: {{"risk_level": "high", "reason": "Customer has not purchased in 67 days."}}
"""
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    raw = response.choices[0].message.content.strip()
    # strip markdown code blocks if model adds them
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)

print("Chain 1 ready — classify_churn() function built")

# ── Test on first row ─────────────────────────────────────────────────────
test_row = df.iloc[0]
result = classify_churn(
    test_row['purchase_count_90d'],
    test_row['days_since_last_purchase'],
    test_row['avg_order_value']
)
print(f'Customer   : {test_row["customer_id"]}')
print(f'Risk level : {result["risk_level"]}')
print(f'Reason     : {result["reason"]}')

Azure OpenAI client ready — gpt-5.4-nano
Chain 1 ready — classify_churn() function built
Customer   : C1001
Risk level : low
Reason     : Customer has made 8 purchases and has purchased within the last 3 days (fewer than 30 days since last purchase).

## Cell 6 — Build Chain 2: Outreach Message Generator

> **Learner task starts here.**  
> The base prompt below generates a generic message.  
> Your task: modify the prompt so that high-risk customers get a **10% discount offer**  
> and the message mentions the **top_product_category** they buy most.
>
> Rules: message must be under 4 sentences. Do not mention 'churn' or 'risk score'.

In [70]:
# ── Chain 2 — Outreach Message Generator ─────────────────────────────────

def generate_message(risk_level, reason, top_product_category):

    # ── BASE PROMPT — works as-is ─────────────────────────────────────────
    # ── LEARNER TASK: modify the section marked below ─────────────────────
    prompt = f"""
You are a customer success manager at a retail company.

A customer has been classified as {risk_level} churn risk.
Reason: {reason}
Their most purchased category: {top_product_category}

Write a short, friendly outreach message that a sales rep would send
to this customer. Match the tone to the risk level:
- High risk: urgent and empathetic
- Medium risk: warm check-in, ask how we can help
- Low risk: appreciative, mention loyalty reward

# LEARNER TASK: add these two rules to the prompt above:
# 1. If risk_level is high, include exactly 10% off their next
#    {top_product_category} purchase as a specific offer
# 2. Keep the message under 4 sentences
# 3. Do not mention churn, risk score, or any internal metric

Return ONLY valid JSON. No markdown, no code blocks.
Example: {{"outreach_message": "Hi! We noticed it has been a while..."}}
"""

    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)

print('✅ Chain 2 ready — generate_message() function built')

# ── Test on one high-risk and one low-risk row ────────────────────────────
high_risk_row = df[df['churn_label'] == 1].iloc[0]
low_risk_row  = df[df['churn_label'] == 0].iloc[0]

print('\n── High-risk customer test ──')
result_high = generate_message('high', 'Customer has not purchased in 67 days', high_risk_row['top_product_category'])
print(f'Category : {high_risk_row["top_product_category"]}')
print(f'Message  : {result_high["outreach_message"]}')

print('\n── Low-risk customer test ──')
result_low = generate_message('low', 'Customer purchased 8 times in 90 days', low_risk_row['top_product_category'])
print(f'Category : {low_risk_row["top_product_category"]}')
print(f'Message  : {result_low["outreach_message"]}')

✅ Chain 2 ready — generate_message() function built

── High-risk customer test ──
Category : Clothing
Message  : Hi there—it's been a little while since your last Clothing purchase, and we’d love to help you get back to feeling great. As a thank-you, here’s 10% off your next Clothing order. Just use code CLOTHING10 at checkout. If you’re looking for something specific, tell us what style you want and we’ll point you to the right picks!

── Low-risk customer test ──
Category : Electronics
Message  : Hi there—thanks for being such an active shopper, especially in Electronics! Since you’ve purchased with us 8 times in the last 90 days, we’d love to reward your loyalty with early access to our latest Electronics deals. If there’s anything specific you’re looking for next, just reply and we’ll help you find it.

## Cell 7 — Run both chains on all customers

In [63]:
import time
import json

results = []

# ── Chain 2 — outreach message generator ─────────────────────────────────
def generate_message(risk_level, reason, top_product_category):
    prompt = f"""
You are a customer success manager at a retail company.

A customer has been classified as {risk_level} churn risk.
Reason: {reason}
Their most purchased category: {top_product_category}

Write a short, friendly outreach message (2-3 sentences) that a sales rep
would send to this customer. Match the tone to the risk level:
- High risk: urgent, empathetic — include a 10% discount off their next {top_product_category} purchase
- Medium risk: warm check-in, ask how we can help
- Low risk: appreciative, mention a loyalty reward

# LEARNER TASK: the high-risk message must include the 10% offer
# and mention {top_product_category} specifically.
# Keep under 4 sentences. Do not mention churn or risk score.

Return ONLY valid JSON.
Example: {{"outreach_message": "Hi! We noticed it has been a while..."}}
"""
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)

# ── Run both chains on all customers ─────────────────────────────────────
print(f'Running chains on {len(df)} customers...')
print('─' * 50)

for i, row in df.iterrows():
    try:
        # Chain 1 — classify risk
        classification = classify_churn(
            row['purchase_count_90d'],
            row['days_since_last_purchase'],
            row['avg_order_value']
        )

        # Chain 2 — generate message
        message = generate_message(
            classification['risk_level'],
            classification['reason'],
            row['top_product_category']
        )

        results.append({
            'date'             : TODAY,
            'customer_id'      : row['customer_id'],
            'purchase_count_90d': row['purchase_count_90d'],
            'days_since_last'  : row['days_since_last_purchase'],
            'avg_order_value'  : row['avg_order_value'],
            'top_category'     : row['top_product_category'],
            'risk_level'       : classification['risk_level'],
            'reason'           : classification['reason'],
            'outreach_message' : message['outreach_message']
        })

        if i < 5 or classification['risk_level'] == 'high':
            print(f"  {row['customer_id']} → {classification['risk_level'].upper()}")

        time.sleep(0.3)

    except Exception as e:
        print(f"  ⚠️  {row['customer_id']} failed: {e}")
        results.append({
            'date': TODAY, 'customer_id': row['customer_id'],
            'risk_level': 'error', 'reason': str(e), 'outreach_message': ''
        })

results_df = pd.DataFrame(results)

print('─' * 50)
print(f'✅ Done — {len(results_df)} rows processed')
print(results_df['risk_level'].value_counts().to_string())
print()
results_df.head()

Running chains on 200 customers...
──────────────────────────────────────────────────
  C1001 → LOW
  C1002 → HIGH
  C1003 → LOW
  C1004 → HIGH
  C1005 → LOW
  C1006 → HIGH
  C1008 → HIGH
  C1009 → HIGH
  C1011 → HIGH
  C1013 → HIGH
  C1016 → HIGH
  C1018 → HIGH
  C1020 → HIGH
  C1023 → HIGH
  C1025 → HIGH
  C1027 → HIGH
  C1029 → HIGH
  C1030 → HIGH
  C1032 → HIGH
  C1034 → HIGH
  C1036 → HIGH
  C1037 → HIGH
  C1039 → HIGH
  C1041 → HIGH
  C1043 → HIGH
  C1044 → HIGH
  C1046 → HIGH
  C1048 → HIGH
  C1050 → HIGH
  C1051 → HIGH
  C1053 → HIGH
  C1055 → HIGH
  C1058 → HIGH
  C1060 → HIGH
  C1062 → HIGH
  C1065 → HIGH
  C1067 → HIGH
  C1069 → HIGH
  C1072 → HIGH
  C1074 → HIGH
  C1076 → HIGH
  C1078 → HIGH
  C1079 → HIGH
  C1081 → HIGH
  C1083 → HIGH
  C1086 → HIGH
  C1088 → HIGH
  C1090 → HIGH
  C1093 → HIGH
  C1095 → HIGH
  C1097 → HIGH
  C1100 → HIGH
  C1102 → HIGH
  C1104 → HIGH
  C1106 → HIGH
  C1108 → HIGH
  C1111 → HIGH
  C1113 → HIGH
  C1115 → HIGH
  C1118 → HIGH
  C1120 → HIGH
  C1122 → HIGH
  C1125 → HIGH
  C1127 → HIGH
  C1129 → HIGH
  C1131 → HIGH
  C1132 → HIGH
  C1134 → HIGH
  C1136 → HIGH
  C1138 → HIGH
  C1140 → HIGH
  C1142 → HIGH
  C1143 → HIGH
  C1145 → HIGH
  C1147 → HIGH
  C1149 → HIGH
  C1150 → HIGH
  C1152 → HIGH
  C1154 → HIGH
  C1157 → HIGH
  C1159 → HIGH
  C1161 → HIGH
  C1164 → HIGH
  C1166 → HIGH
  C1168 → HIGH
  C1170 → HIGH
  C1172 → HIGH
  C1175 → HIGH
  C1177 → HIGH
  C1179 → HIGH
  C1182 → HIGH
  C1184 → HIGH
  C1186 → HIGH
  C1189 → HIGH
  C1191 → HIGH
  C1193 → HIGH
  C1196 → HIGH
  C1198 → HIGH
  C1200 → HIGH
──────────────────────────────────────────────────
✅ Done — 200 rows processed
risk_level
high      96
low       74
medium    30

,date,customer_id,purchase_count_90d,days_since_last,avg_order_value,top_category,risk_level,reason,outreach_message
0,2026-06-07,C1001,8,3,245.50,Electronics,low,Customer has made 6+ purchases and has not gon...,Hi there—thanks for your recent Electronics pu...
1,2026-06-07,C1002,1,67,89.00,Clothing,high,Customer has only 1 purchase and has gone 67 d...,Hi there—it's been a little while since your l...
2,2026-06-07,C1003,6,5,312.75,Groceries,low,Customer has made 6 purchases and has purchase...,Hi there! Thanks for being such a loyal Grocer...
3,2026-06-07,C1004,2,54,125.00,Electronics,high,Customer has made only 2 purchases and has not...,"Hi there—we haven’t seen you in a bit, and we’..."
4,2026-06-07,C1005,9,2,198.25,Clothing,low,Customer has made 9 purchases and has purchase...,Hi there! Thanks for your recent Clothing purc...

## Cell 8 — Write results to Google Sheet

> This is what the sales team reads every morning — not Colab, not a CSV.  
> n8n will also read this sheet at 9 AM to trigger the Slack alerts.

In [64]:
from google.colab import auth
import gspread
from gspread_dataframe import set_with_dataframe
from google.auth import default

# Authenticate with Google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Open the sheet and write to the Results tab
spreadsheet = gc.open_by_key(SHEET_ID)

try:
    worksheet = spreadsheet.worksheet('Results')
except gspread.exceptions.WorksheetNotFound:
    worksheet = spreadsheet.add_worksheet(title='Results', rows=10000, cols=20)

# Append — do not overwrite historical data
existing = worksheet.get_all_values()
start_row = len(existing) + 1

if start_row == 1:
    # First time — write with headers
    set_with_dataframe(worksheet, results_df)
else:
    # Append rows below existing data
    set_with_dataframe(worksheet, results_df, row=start_row, include_column_header=False)

print(f'✅ Results written to Google Sheet')
print(f'   Sheet ID  : {SHEET_ID}')
print(f'   Tab       : Results')
print(f'   Rows added: {len(results_df)}')
print(f'   Total rows: {start_row + len(results_df) - 1}')

✅ Results written to Google Sheet
   Sheet ID  : 1rW3TCKv2YucLqHl17q3eNKjThWCbxCHqIMHwOAfJI24
   Tab       : Results
   Rows added: 200
   Total rows: 201

## Cell 9 — Preview high-risk customers

> These are the customers the Slack alert will fire for.  
> The sales team sees these in #sales-alerts at 9 AM.

In [65]:
high_risk = results_df[results_df['risk_level'] == 'high'][[
    'customer_id', 'days_since_last', 'top_category', 'reason', 'outreach_message'
]]

print(f'🔴 High-risk customers today: {len(high_risk)}')
print('─' * 60)

for _, r in high_risk.iterrows():
    print(f"\n{r['customer_id']} — {r['days_since_last']} days since last purchase")
    print(f"Reason  : {r['reason']}")
    print(f"Message : {r['outreach_message']}")
    print('─' * 60)

🔴 High-risk customers today: 96
────────────────────────────────────────────────────────────

C1002 — 67 days since last purchase
Reason  : Customer has only 1 purchase and has gone 67 days since the last purchase, which meets the high churn risk criteria.
Message : Hi there—it's been a little while since your last purchase, and I wanted to check in. We’d love to help you get back to your style: enjoy 10% off your next Clothing purchase with us. If there’s anything you’re looking for, tell us what you need and we’ll point you to the right picks!
────────────────────────────────────────────────────────────

C1004 — 54 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 54 days, indicating high churn risk.
Message : Hi there—we haven’t seen you in a bit, and we’d really hate for you to miss out on something you’ll love. Since you’ve shopped Electronics with us before, we’d like to offer you 10% off your next Electronics purchase—just use code ELECTRONICS10 at checkout. If there’s anything we can help you find, reply anytime!
────────────────────────────────────────────────────────────

C1006 — 72 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 72 days, indicating high churn risk.
Message : Hi there—I'm really sorry we haven’t seen you in a bit. We’d love to welcome you back for your next Groceries purchase with 10% off when you use the offer on your next order. If there’s anything we can help you find or restock, just reply here!
────────────────────────────────────────────────────────────

C1008 — 41 days since last purchase
Reason  : Customer has made only 3 purchases and has not purchased in 41 days, which indicates elevated churn risk.
Message : Hi there—it's been a little while since your last order, and we’d hate for you to miss out. We’d love to help you get back into your style: enjoy 10% off your next Clothing purchase with us. If there’s anything you’re looking for, just reply and we’ll point you to the right picks!
────────────────────────────────────────────────────────────

C1009 — 61 days since last purchase
Reason  : Customer has only 1 purchase and has gone 61 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a little while since your last purchase, and I wanted to make sure you’re doing well. If you’d like to grab something new in Electronics, we’d love to help: enjoy 10% off your next Electronics purchase with us. Just use code ELECTRONICS10 at checkout.
────────────────────────────────────────────────────────────

C1011 — 58 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 58 days, which indicates elevated churn risk.
Message : Hi there! We’ve missed you—since it’s been a bit, we want to make it easy to get back to your favorites. Enjoy 10% off your next Clothing purchase with us; just use code WELCOME10 at checkout. Hope to see you soon!
────────────────────────────────────────────────────────────

C1013 — 69 days since last purchase
Reason  : Customer has only 1 purchase and has gone 69 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a bit since your last Groceries order, and we wanted to make it easy to stock up again. For your next Groceries purchase, enjoy 10% off when you use code WELCOME10 at checkout. If there’s anything you’re looking for, just reply and we’ll help!
────────────────────────────────────────────────────────────

C1016 — 75 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 75 days, indicating high churn risk.
Message : Hi there—we miss you! We’d love to help you get back into your favorite Clothing styles, so here’s 10% off your next Clothing purchase. If there’s anything you’re looking for, just reply and we’ll point you to the best options.
────────────────────────────────────────────────────────────

C1018 — 49 days since last purchase
Reason  : Customer has only 2 purchases and has not purchased in 49 days, which indicates elevated churn risk.
Message : Hi there—hope you’re doing well. We noticed it’s been a bit since your last Electronics purchase, and we’d love to help you get back on track. Use code ELECTRONICS10 for 10% off your next Electronics order—if there’s something specific you’re looking for, reply and we’ll point you to the best options.
────────────────────────────────────────────────────────────

C1020 — 63 days since last purchase
Reason  : Customer has only 1 purchase and has gone 63 days since the last purchase, which meets the high churn risk criteria.
Message : Hi there—we noticed it’s been a little while since your last order, and we’d really like to make it easy to get back to your routine. As a thank-you, enjoy 10% off your next Groceries purchase with us. If there’s anything specific you’ve been looking for, reply and we’ll help you find it.
────────────────────────────────────────────────────────────

C1023 — 71 days since last purchase
Reason  : Customer has only 1 purchase and has gone 71 days since the last purchase, which meets the high churn risk criteria.
Message : Hi there—hope you’re doing well! We noticed it’s been a bit since your last Electronics purchase, and we don’t want you to miss out. Use code ELECTRONICS10 for 10% off your next Electronics order with us today.
────────────────────────────────────────────────────────────

C1025 — 52 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 52 days, indicating high churn risk.
Message : Hi there—we’ve missed you! It’s been a bit since your last purchase, and we’d love to help you get back into your Clothing favorites. Use code WELCOME10 for 10% off your next Clothing purchase today.
────────────────────────────────────────────────────────────

C1027 — 68 days since last purchase
Reason  : Customer has only 1 purchase and has gone 68 days since the last purchase, indicating high churn risk.
Message : Hi there—we hope you’re doing well! It’s been a bit since your last order, and we’d love to help you restock your Groceries. Use code GROCERIES10 for 10% off your next Groceries purchase—just for you.
────────────────────────────────────────────────────────────

C1029 — 22 days since last purchase
Reason  : Customer has made only 4 purchases and has gone 22 days since the last purchase, which does not meet the medium/low criteria.
Message : Hi there—it's been a little while since your last order, and we don’t want you to miss out on the Electronics you love. As a thank-you, here’s 10% off your next Electronics purchase when you’re ready to shop again. If there’s anything specific you’re looking for, just reply and we’ll help you find it!
────────────────────────────────────────────────────────────

C1030 — 77 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 77 days, indicating high churn risk.
Message : Hi there—it's been a little while since your last purchase, and I don’t want you to miss out. We’d love to help you get back into something you’ll love: enjoy 10% off your next Clothing purchase. If you tell us what style you’re into, we can recommend a few great picks!
────────────────────────────────────────────────────────────

C1032 — 46 days since last purchase
Reason  : Customer has only 2 purchases and has not purchased in 46 days, which indicates elevated churn risk.
Message : Hi there—thanks for being with us! We noticed it’s been a little while since your last purchase, and we’d love to help you get back to your Electronics favorites. Use code ELECTRONICS10 for 10% off your next Electronics purchase—just in time for your next upgrade!
────────────────────────────────────────────────────────────

C1034 — 65 days since last purchase
Reason  : Customer has only 1 purchase and has gone 65 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a little while since your last order, and we’d love to make it easier to get back into your routine. Here’s 10% off your next Groceries purchase with us—just use code GROCERIES10 at checkout. If there’s anything we can help with, reply anytime!
────────────────────────────────────────────────────────────

C1036 — 38 days since last purchase
Reason  : Customer has made only 3 purchases and has not purchased in 38 days, which indicates elevated churn risk under the given rules.
Message : Hi there—we miss you! If you’ve been meaning to refresh your wardrobe, we’d love to help with 10% off your next Clothing purchase. Just use code CLOTHING10 at checkout, and let us know if you need any recommendations.
────────────────────────────────────────────────────────────

C1037 — 73 days since last purchase
Reason  : Customer has only 1 purchase and has gone 73 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a bit since your last order, and we don’t want you to miss out. If you’re thinking about anything in Electronics, take 10% off your next Electronics purchase with us. Reply anytime if you’d like help finding the right item!
────────────────────────────────────────────────────────────

C1039 — 55 days since last purchase
Reason  : Customer has only 2 purchases and has not purchased in 55 days, indicating high churn risk.
Message : Hi there—it's been a little while since your last purchase, and we’d really love to see you back. As a thank-you, enjoy 10% off your next Clothing order with us. What styles are you shopping for right now?
────────────────────────────────────────────────────────────

C1041 — 70 days since last purchase
Reason  : Customer has only 1 purchase and has gone 70 days since the last purchase, which meets the high churn risk criteria.
Message : Hi there—we’re sorry it’s been a while since your last purchase. We’d love to help you get back on track with 10% off your next Groceries order. If there’s anything you need or want us to stock more of, just reply and we’ll do our best!
────────────────────────────────────────────────────────────

C1043 — 25 days since last purchase
Reason  : Customer has made only 4 purchases and has gone 25 days since the last purchase, which does not meet the low-risk criteria and indicates elevated churn risk.
Message : Hi there—just checking in because it’s been a little while since your last purchase. We’d love to help you get back to what you like: enjoy 10% off your next Electronics order with us. If you tell us what you’re shopping for, we can point you to the best options!
────────────────────────────────────────────────────────────

C1044 — 79 days since last purchase
Reason  : Customer has only 1 purchase and has gone 79 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a little while since your last order, and I wanted to make sure you’re all set. If you’d like, take 10% off your next Clothing purchase with us; just use code CLOTHING10 at checkout. We’d love to help you find something you’ll love!
────────────────────────────────────────────────────────────

C1046 — 51 days since last purchase
Reason  : Customer has only 2 purchases and has gone 51 days since the last purchase, indicating elevated churn risk.
Message : Hi there—sorry we haven’t seen you in a bit. We’d love to help you find something new in Electronics, and as a thank-you, take 10% off your next Electronics purchase with us. If you tell me what you’re shopping for, I’ll point you to the best options.
────────────────────────────────────────────────────────────

C1048 — 66 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 66 days, which meets the high churn risk criteria.
Message : Hi there—it's been a little while since your last Groceries order, and we wanted to check in. If you’re planning to stock up soon, we’d love to offer you 10% off your next Groceries purchase. Just use the discount at checkout and thank you for shopping with us!
────────────────────────────────────────────────────────────

C1050 — 32 days since last purchase
Reason  : Customer has made only 3 purchases and has gone 32 days since the last purchase, indicating elevated churn risk.
Message : Hi there! We miss you—if you’ve been meaning to refresh your wardrobe, we’d love to help. Enjoy 10% off your next Clothing purchase with us; just use code WELCOME10 at checkout. Reply and tell us what style you’re looking for—we’re here to help!
────────────────────────────────────────────────────────────

C1051 — 74 days since last purchase
Reason  : Customer has only 1 purchase and has gone 74 days since the last purchase, indicating high churn risk.
Message : Hi there—we’ve missed you lately, and I wanted to reach out before you forget about us. Since you’ve shopped Electronics with us before, here’s a 10% discount off your next Electronics purchase. If there’s anything you’re looking for, reply and we’ll help you find the right option fast!
────────────────────────────────────────────────────────────

C1053 — 48 days since last purchase
Reason  : Customer has only 2 purchases and has gone 48 days since the last purchase, indicating elevated churn risk.
Message : Hi there—it's been a little while since your last order. We’d love to help you find something you’ll love in Clothing, so please enjoy 10% off your next Clothing purchase with us. Want a hand with sizing or recommendations?
────────────────────────────────────────────────────────────

C1055 — 62 days since last purchase
Reason  : Customer has only 1 purchase and has gone 62 days since the last purchase, indicating high churn risk.
Message : Hi there—hope you’re doing well! We noticed it’s been a bit since your last Groceries order, and we’d love to help make your next trip easier. Use code GROCERIES10 for 10% off your next Groceries purchase.
────────────────────────────────────────────────────────────

C1058 — 76 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 76 days, indicating high churn risk.
Message : Hi there—it's been a little while since your last order, and we’d hate for you to miss out. If you’re still shopping for something in Clothing, here’s 10% off your next Clothing purchase with us. Just use code WELCOME10 at checkout—hope to see you soon!
────────────────────────────────────────────────────────────

C1060 — 57 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 57 days, indicating elevated churn risk.
Message : Hi there—hope you’re doing well! We noticed it’s been a bit since your last purchase, and we don’t want you to miss out on great Electronics picks. Use code ELECTRONICS10 for 10% off your next Electronics order with us today.
────────────────────────────────────────────────────────────

C1062 — 69 days since last purchase
Reason  : Customer has only 1 purchase and has gone 69 days since the last purchase, which meets the high-risk criteria.
Message : Hi there—sorry it’s been a little while since your last order. We’d love to help you get back on track with your Groceries: enjoy 10% off your next Groceries purchase. If there’s anything we can do to make shopping easier, just reply here!
────────────────────────────────────────────────────────────

C1065 — 72 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 72 days, which meets the high churn risk criteria.
Message : Hi there—it's been a little while since your last order, and we didn’t want you to miss out. If you’re planning another Electronics purchase soon, we’d love to offer you 10% off your next one. Just use the code ELECTRONICS10 at checkout!
────────────────────────────────────────────────────────────

C1067 — 53 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 53 days, indicating high churn risk.
Message : Hi there—it's been a bit since your last order, and I didn’t want you to miss out. We’d love to help you find something new in Clothing, and you can get 10% off your next Clothing purchase with us. Reply and tell me what style you’re shopping for!
────────────────────────────────────────────────────────────

C1069 — 64 days since last purchase
Reason  : Customer has only 1 purchase and has gone 64 days since the last purchase, which meets the high-risk criteria.
Message : Hi there—it's been a little while since your last order, and we’d love to help you get back on track. As a thank-you, enjoy 10% off your next Groceries purchase with us. If there’s anything you need, just reply and we’ll make it easy!
────────────────────────────────────────────────────────────

C1072 — 78 days since last purchase
Reason  : Customer has only 1 purchase and has gone 78 days since the last purchase, indicating high churn risk.
Message : Hi there—it's been a little while since your last purchase, and we’d really hate for you to miss out. We’d love to help you get back into your style with 10% off your next Clothing order. If you tell us what you’re shopping for, we can point you to the best matches!
────────────────────────────────────────────────────────────

C1074 — 50 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 50 days, indicating high churn risk.
Message : Hi there—it's been a bit since your last order, and I wanted to make sure you’re all set. If you’re looking to grab something new, we’d love to help with 10% off your next Electronics purchase. Just use code ELECTRONICS10 at checkout.
────────────────────────────────────────────────────────────

C1076 — 67 days since last purchase
Reason  : Customer has only 1 purchase and has gone 67 days since the last purchase, which meets the high churn risk criteria.
Message : Hi there—it's been a little while since your last order, and I wanted to check in. We’d love to help make it easy to get back to your routine: enjoy 10% off your next Groceries purchase. If there’s anything we can do to help, just reply here!
────────────────────────────────────────────────────────────

C1078 — 39 days since last purchase
Reason  : Customer has made only 3 purchases and has gone 39 days since the last purchase, indicating elevated churn risk under the given rules.
Message : Hi there—it's been a little while since your last purchase, and we’d love to help you get back into your groove. As a thank-you, here’s 10% off your next Clothing purchase. If you tell me what style you’re shopping for, I can point you to the best picks!
────────────────────────────────────────────────────────────

C1079 — 75 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 75 days, indicating high churn risk.
Message : Hi there—sorry it’s been a bit since your last purchase! We’d love to help you get back to your favorite Electronics: enjoy 10% off your next Electronics order with us. If there’s anything you’re looking for, just reply and we’ll point you to the best options.
────────────────────────────────────────────────────────────

C1081 — 56 days since last purchase
Reason  : Customer has made only 2 purchases and has not purchased in 56 days, indicating high churn risk.
Message : Hi there! We’ve missed you—since it’s been a little while, we wanted to make it easy to get back to your wardrobe. Enjoy 10% off your next Clothing purchase with us; just use code WELCOME10 at checkout. Hope to see you soon!
────────────────────────────────────────────────────────────

C1083 — 71 days since last purchase
Reason  : Customer has only 1 purchase and has not purchased in 71 days, indicating high churn risk.
Message : Hi there— we’ve missed you! If you’d like, take 10% off your next Groceries purchase with us; just use code GRO10 at checkout. What can we do to make your next trip even better?
────────────────────────────────────────────────────────────

C1086 — 80 days since last purchase

## Cell 10 — Save results locally (backup)

> Also saves a timestamped CSV to Drive as an audit trail.

In [69]:
OUTPUT_PATH = os.path.join(DRIVE_FOLDER, f'results_{TODAY}.csv')
results_df.to_csv(OUTPUT_PATH, index=False)
print(f'✅ Backup saved to Drive: results_{TODAY}.csv')

# Also download to local machine
from google.colab import files
results_df.to_csv('retailco_results_today.csv', index=False)
files.download('retailco_results_today.csv')
print('✅ Downloaded to your machine')

✅ Backup saved to Drive: results_2026-06-07.csv

✅ Downloaded to your machine

In [68]:
# Fix headers — write them to row 1
header = ['date', 'customer_id', 'purchase_count_90d', 'days_since_last',
          'avg_order_value', 'top_category', 'risk_level', 'reason', 'outreach_message']

worksheet.update('A1', [header])
print(' Headers added')

 Headers added

/tmp/ipykernel_10934/2307780670.py:5: DeprecationWarning: The order of arguments in worksheet.update() has changed. Please pass values first and range_name secondor used named arguments (range_name=, values=)
  worksheet.update('A1', [header])

---
## How n8n reads the results

Once this notebook runs, n8n takes over:

```
Schedule Trigger (9 AM)
        ↓
Google Sheets node — reads the Results tab
        ↓
IF node — risk_level equals 'high'
        ↓ TRUE
Slack node — posts customer_id + reason + outreach_message to #sales-alerts
        ↓ FALSE
(no action — low/medium customers tracked in sheet only)
```

The Colab notebook is the AI engine.  
n8n is the plumbing that connects it to the client's world.  
The sales team never opens Colab.